version: '3.9' # INI PERBAIKAN UTAMA

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  webui:
    image: ghcr.io/open-webui/open-webui:v0.6.30
    container_name: open-webui
    restart: unless-stopped
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - WEBUI_SECRET_KEY=KEY_SECRET_HAHAH_WKWKWK
      - PORT=8080 
      - LOG_LEVEL=debug
    ports:
      - "3001:8080"
    depends_on:
      - ollama

volumes:
  ollama_data: