#version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    entrypoint: /bin/sh -c "ollama serve & sleep 5 && ollama pull deepseek-r1:7b && wait"

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    ports:
      - "3000:8080"
    depends_on:
      - ollama

volumes:
  ollama_data:
